### ISSUE TITLE
reported scannet200 running time in the supplementary 

### ISSUE THREAD

**Issue by aminebdj** [VinAIResearch/Open3DIS#2]
Dear authors, 

I tried to run the code on the scannet200 dataset on an A100 40GB GPU; computing the grounded features alone takes 1h15min per scene, which makes the estimated total time more than 390 hours. Could you please share some details on the setting that gave the reported time in your paper supplementary material (the table is attached below)?

Please find below some details on the data I am using:

RGB image dimension: 640, 480 (resized similar to OpenMask3D)
Image interval: 2

![image](https://github.com/VinAIResearch/Open3DIS/assets/95423980/abe5b075-977a-4da1-8cb0-61952819988e)

Many thanks,
Mohamed

**Comment by PhucNDA** [comment]
Hi @aminebdj,

We render 5 images each time from .sens files, so `subsampling_factor = 5 * image_interval`. 
`image_interval = 2` meaning that the `subsampling_factor = 10 `for each scene. (The same as OpenMask3D). Regarding the average number of images per scene, our method, using a subsampling factor of 10, processes approximately 200-300 images per scene. You can verify this by examining our sample Scannet200 scene [here](https://drive.google.com/file/d/1t2a5XQqkrauJo1iqheO0oJKQ8PeJBRR0/view?usp=sharing)

It's worth noting that the number of images per scene in Scannet200 varies. Thus, considering the processing time for the largest scene multiplied by the number of scenes may provide an upper bound estimation of the total processing time.

If you have any questions, feel free to discuss here.

Best,
PhucNDA.

**Comment by aminebdj** [comment]
Hey @PhucNDA,

Thanks a lot for your reply,

I re-ran the code with a subsampling factor of 10 this time, but the estimated time to compute the grounded features is 48 hours. To confirm, I tried to run grounded-sam separately for the same frames of a single scene, and the inference takes around 2.5~3 seconds per frame; since the average number of frames for scannet200 is around 200, the total time is 43 hours. Do you have the same inference time for a single frame in your case?

Many thanks,
Mohamed

**Comment by PhucNDA** [comment]
HI @aminebdj,

I can confirm that executing the 2D segmenter (Grounded-SAM) is quite time-consuming, taking approximately 48 hours, as you've mentioned. To optimize efficiency, it may be prudent to initially generate 2D segmentations for 312 scenes on Scannet200 and store them offline, rather than recalculating them for each run. In our supplementary materials, we detail the time required for aggregating point cloud CLIP features, assuming that 2D masks are already available.
For faster 2D segmenter, you can consider [Mobile SAM](https://github.com/ChaoningZhang/MobileSAM), [EfficientViT](https://github.com/mit-han-lab/efficientvit), etc. for faster mask generation while achieving the same or higher performance as Grounded SAM.

Best.

**Comment by aminebdj** [comment]
Hey @PhucNDA ,

Thanks a lot for the clarification.

Best,
Mohamed.
