### ISSUE TITLE
Inconsistent qualitative results

### ISSUE THREAD

**Issue by aminebdj** [VinAIResearch/Open3DIS#4]
Hello,

I ran the script to get the 3D proposals from the 2D masks on the sample provided [here](https://drive.google.com/file/d/1t2a5XQqkrauJo1iqheO0oJKQ8PeJBRR0/view?usp=sharing), but I couldn't get the same qualitative results as in the paper (details on the results I got are bellow). What post-processing did you use to get the proposals shared in the paper, and what mask scores did you use to perform the post-processing?

Also, you mentioned here that NMS was applied after combining both 3D and 2D-3D proposals
![image](https://github.com/VinAIResearch/Open3DIS/assets/95423980/99fa18e4-6764-40a8-aa2c-35ad134fa12d)
However, it seems that the NMS section [here](https://github.com/VinAIResearch/Open3DIS/blob/ce4abaf904da091075b3dde1a936ee435facd5bd/tools/generate_3d_inst.py#L137) is commented out in the code.

The results I got (from 2D only):
![image](https://github.com/VinAIResearch/Open3DIS/assets/95423980/140be72a-b1cc-4237-bf20-acbe2a76d250)

Results reported in the paper:
![image](https://github.com/VinAIResearch/Open3DIS/assets/95423980/1cd9baf3-6209-4421-9e71-dd6303e4fe34)

Thanks in advance for your assistance,

**Comment by PhucNDA** [comment]
Hi @aminebdj,
![agg](https://github.com/VinAIResearch/Open3DIS/assets/108280892/950fbdaa-4bc4-4ee2-8581-90143e97dfc8)

Initially, we employed NMS (Non-Maximum Suppression) to eliminate redundant masks. However, we observed that this step did not significantly impact performance. Consequently, we opted to forgo any post-processing steps to retain as many masks as possible (not leveraging post-processing steps to achieve well-looking masks). The results you showed appear to be somewhat similar to ours. To validate the processed masks, you can run class-agnostic mask validation script and check on [project page](https://open3dis.github.io/) .
For the visualization issue, on the first and second levels, we use the visualizations generated from the source code. However, for the last two levels, we discovered that our visualizations could overwhelm readers due to the abundance of lifted 2D masks. Therefore, we opted to utilize ground truth annotations for these final two levels to enhance visualization clarity. We apologize for any confusion this may have caused to you.

Best.

**Comment by aminebdj** [comment]
Hey @PhucNDA,

Thanks a lot for the explanation.
