### ISSUE TITLE
Could you share pre-computed predictions of Open3DIS?

### ISSUE THREAD

**Issue by ayushjain1144** [VinAIResearch/Open3DIS#8]
Hi,

Thank you for your awesome work and releasing the code. Would it be possible to share the generated segmentation masks and classes from your pipeline on scannet? That would be very helpful! Thank you.

**Comment by PhucNDA** [comment]
Hi, @ayushjain1144,

I have just updated the precomputed masks and class of Open3DIS for Scannet200 dataset. You can check it [here](https://github.com/VinAIResearch/Open3DIS/blob/main/docs/DATA.md)

Best.

**Comment by ayushjain1144** [comment]
Hi @PhucNDA, thank you so much for the quick response! Would it be possible to also provide the precomputed results with "2D only" version on scannet200? (That gets about ~19mAP)

**Comment by PhucNDA** [comment]
Hi @ayushjain1144,

Sorry for the late reply due to issue #10 . I have uploaded the precomputed masks+class for (2D only) using GSAM masks at [GoogleDrive](https://drive.google.com/file/d/1EV2BuRn8Qu889EnmI8vUc2y9tmRTnVPW/view?usp=sharing).  I will update the repo, soon.

![image](https://github.com/VinAIResearch/Open3DIS/assets/108280892/328e54d8-5579-42bb-b35a-7b244929e5ed)

Best.

**Comment by ayushjain1144** [comment]
Thanks a lot!!!
